title: Lumos RL Workspace
description: A documentation of develop humanoid motion control policy
theme: just-the-docs

url: https://lumosrobotics.github.io

aux_links:
  github: https://github.com/LumosRobot/lumos_ws.git

plugins:
  - jekyll-default-layout
